language: node_js
node_js:
  - "0.10"
script: npm test --coverage
after_success:
- npm run coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d1ec4245f90231619d30
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false